# Generated by Django 5.1.5 on 2025-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='uri',
            field=models.CharField(blank=True, null=True),
        ),
    ]
